[package]
edition = "2024"
name    = "cite-otter"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
