[package]
edition = "2024"
name    = "cite-otter"
version = "0.2.0"

[dependencies]
anyhow = "1.0"
clap = { features = [
  "derive",
], version = "4.3" }
serde = { features = [
  "derive",
], version = "1.0" }
serde_json = "1.0"
